import { ModelAnimConfig } from '@/types';

export const ANIM_JOINTS_CONFIG: ModelAnimConfig = {
  hips: "mixamorigHips",
  spine: "mixamorigSpine",
  spine1: "mixamorigSpine1",
  spine2: "mixamorigSpine2",
  neck: "mixamorigNeck",
  head: "mixamorigHead",
  shoulderLeft: "mixamorigLeftShoulder",
  shoulderRight: "mixamorigRightShoulder",
  
  upLegLeft: "mixamorigLeftUpLeg",
  legLeft: "mixamorigLeftLeg",
  footLeft: "mixamorigLeftFoot",
  upLegRight: "mixamorigRightUpLeg",
  legRight: "mixamorigRightLeg",
  footRight: "mixamorigRightFoot",

  armLeft: "mixamorigLeftArm",
  foreArmLeft: "mixamorigLeftForeArm",
  handLeft: "mixamorigLeftHand",
  
  armRight: "mixamorigRightArm",
  foreArmRight: "mixamorigRightForeArm",
  handRight: "mixamorigRightHand",

  thumbThumb1Left: "mixamorigLeftHandThumb1",
  thumbThumb2Left: "mixamorigLeftHandThumb2",
  thumbThumb3Left: "mixamorigLeftHandThumb3",
  index1Left: "mixamorigLeftHandIndex1",
  index2Left: "mixamorigLeftHandIndex2",
  index3Left: "mixamorigLeftHandIndex3",
  middle1Left: "mixamorigLeftHandMiddle1",
  middle2Left: "mixamorigLeftHandMiddle2",
  middle3Left: "mixamorigLeftHandMiddle3",
  ring1Left: "mixamorigLeftHandRing1",
  ring2Left: "mixamorigLeftHandRing2",
  ring3Left: "mixamorigLeftHandRing3",
  pinky1Left: "mixamorigLeftHandPinky1",
  pinky2Left: "mixamorigLeftHandPinky2",
  pinky3Left: "mixamorigLeftHandPinky3",

  thumbThumb1Right: "mixamorigRightHandThumb1",
  thumbThumb2Right: "mixamorigRightHandThumb2",
  thumbThumb3Right: "mixamorigRightHandThumb3",
  index1Right: "mixamorigRightHandIndex1",
  index2Right: "mixamorigRightHandIndex2",
  index3Right: "mixamorigRightHandIndex3",
  middle1Right: "mixamorigRightHandMiddle1",
  middle2Right: "mixamorigRightHandMiddle2",
  middle3Right: "mixamorigRightHandMiddle3",
  ring1Right: "mixamorigRightHandRing1",
  ring2Right: "mixamorigRightHandRing2",
  ring3Right: "mixamorigRightHandRing3",
  pinky1Right: "mixamorigRightHandPinky1",
  pinky2Right: "mixamorigRightHandPinky2",
  pinky3Right: "mixamorigRightHandPinky3",
};
